[package]
name = "ruc"
version = "4.0.1"
authors = ["rust-util-collections","fanhui.x@gmail.com"]
edition = "2021"
description = "Rust Util Collections"
keywords = ["utils", "error-management"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://github.com/rust-util-collections/ruc"
repository = "https://github.com/rust-util-collections/ruc.git"

[dependencies]
once_cell = "1.16"

libc-print = { version = "0.1.20", optional = true }
blake3 = { version = "1.3.1", default-features = false, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
time = { version = "0.3", features = ["formatting"] }

nix = { version = "0.26", optional = true }
rand = { version = "0.8", optional = true }
ssh2 = { package = "ssh2-patched", version = "0.9.4-p1", optional = true }

[features]
default = ["ansi"]

no_std = ["libc-print"]
ansi = []
compact = []
uau = ["nix","rand"]
cmd = []
ssh = ["ssh2"]
crypto = ["blake3"]

full = ["uau","cmd","ssh","crypto"]
