[package]
name = "ruc"
version = "0.6.2"
authors = ["FindoraNetwork"]
edition = "2018"
description = "Rust Util Collection, include a friendly `error-chain` and many other utils."
keywords = ["error", "error-chain"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://github.com/FindoraNetwork/ruc"
repository = "https://github.com/FindoraNetwork/ruc.git"

[dependencies]
lazy_static = "1.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
time = "0.2.23"

[features]
ansi = []
default = ["ansi"]
