[package]
name = "ruc"
version = "6.0.0"
authors = ["hui.fan@mail.ru"]
edition = "2021"
description = "Rust Util Collections"
keywords = ["utils", "error-management"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://github.com/rust-util-collections/ruc"
repository = "https://github.com/rust-util-collections/ruc.git"

[package.metadata.docs.rs]
features = ["full"]

[dependencies]
once_cell = "1.18"

sha3 = { version = "0.10.8", optional = true }

ed25519-zebra = { version = "4.0.0", optional = true }

rand = { version = "0.8", optional = true }
base64 = {version = "0.22.1", optional = true }
hex = {version = "0.4.3", optional = true }

nix = { version = "0.29", features = ["socket"], optional = true }
time = { version = "0.3", features = ["formatting"] }
ssh2 = { version = "0.9.4", optional = true }

serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["ansi"]

ansi = []
compact = []
uau = ["nix","rand"]
cmd = []
ssh = ["ssh2"]
crypto = ["sha3", "ed25519-zebra", "rand", "base64", "hex"]
ser_de = ["serde"]

full = ["uau", "cmd", "ssh", "crypto", "ser_de"]
