[package]
name = "ruc"
version = "1.0.8"
authors = ["rust-util-collections","fanhui.x@gmail.com"]
edition = "2021"
description = "Rust Util Collections"
keywords = ["utils", "error-management"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://github.com/rust-util-collections/RUC"
repository = "https://github.com/rust-util-collections/RUC.git"

[dependencies]
once_cell = "1.10.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nix = { version = "0.23.1", optional = true }
rand = { version = "0.8.5", optional = true }
time = { version = "0.3.6", features = ["formatting"] }

[features]
default = ["ansi"]
ansi = []
compact = []

rich = ["uau", "cmd"]
uau = ["nix", "rand"]
cmd = []
