[package]
name = "ruc"
version = "1.0.2"
authors = ["ccmlm"]
edition = "2021"
description = "Rust Util Collection"
keywords = ["error", "error-chain"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://github.com/ccmlm/RUC"
repository = "https://github.com/ccmlm/RUC.git"

[dependencies]
once_cell = "1.9.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nix = { version = "0.22.1", optional = true }
rand = { version = "0.8.0", optional = true }
time = "0.2.23"

[features]
default = ["ansi"]
ansi = []
compact = []

rich = ["uau", "cmd"]
uau = ["nix", "rand"]
cmd = []
